### ISSUE TITLE
README 加上安裝和啟動說明應該會更好？

### ISSUE THREAD

**Issue by festime** [ComicsReader/reader#22]
Hi
我是從 HackMD 的 contributors 看到你的 Github 和部落格，還有這個專案 :)
看起來很不錯 👍 

一點小建議
我對 JavaScript 生態圈不熟
如果在 Readme 可以加上安裝和啟動的指令
像 HackMD 的那樣
是不是會比較好？

**Comment by paristsai** [comment]
Hello @festime,
我只是路過的，如果想要在自己電腦測這個套件，
你要先把這個專案 clone 下來之後
去 firebase 申請個帳號，把一些相關資訊填到 src/config.js.sample（不確定要不要改名把 config.js.sample 改名成 config.js）
進去專案跟目錄下指令
1. npm i
2. npm run dev
其他的指令可以研究 package.json 裡面的 scripts

**Comment by Yukaii** [comment]
@festime 哈囉，因為最近弄其它專案，這邊暫時處於無限期停工狀態 😓  等最近我自己狀況好一些，會再把這邊的坑補齊。待完成 #1 剩餘事項的時候，會用 Electron builder 壓一版各平臺能直接使用的 binary/installer，目前也有 [Chrome extension 版本](https://chrome.google.com/webstore/detail/comics-reader/bklgednckimmhomhlbdmdhffoamaafib)可以試用。

開發設定如二樓 @paristsai 所說，要把 `config.js.example` 改成 `config.js`，填入 firebase 的 API key，另外 node/npm 環境也要裝好，這個 issue close 掉時我會把 README 的 Getting Started 補齊一些 😅

**Comment by Yukaii** [comment]
@festime 我在 https://github.com/ComicsReader/app/commit/9173005d240fe9eed2ce3dbd92f9436210e2311c 這個 commit 更新了一點說明，若還有問題可以參考 😸
