### ISSUE TITLE
hi 你好 我是 comics scroller 的原作者

### ISSUE THREAD

**Issue by zeroshine** [ComicsReader/reader#36]
看到有人這麼認真幫我把我小時候寫的那麼醜的 code 翻成 electron app 有點感動，首先先向你說聲抱歉code 寫的那麼醜，研究起來一定很辛苦，之前因為開始上班也沒有那麼多的時間維護，其實最近正在改寫中希望可以把它寫漂亮一點

**Comment by Yukaii** [comment]
@zeroshine 我也是 ComicsScroller 的愛用者 😍  用它看了好多部漫畫，感謝你的努力！
